// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package workspace

import (
	"sync"
)

// Ensure that MoqGit does implement Git.
// If this is not the case, regenerate this file with mockery.
var _ Git = &MoqGit{}

// MoqGit is a mock implementation of Git.
//
//	func TestSomethingThatUsesGit(t *testing.T) {
//
//		// make and configure a mocked Git
//		mockedGit := &MoqGit{
//			CheckoutFunc: func(repoDir string, ref string) error {
//				panic("mock out the Checkout method")
//			},
//			CloneFunc: func(repoURL string, targetDir string) error {
//				panic("mock out the Clone method")
//			},
//			FetchFunc: func(repoDir string) error {
//				panic("mock out the Fetch method")
//			},
//			RevParseFunc: func(repoDir string, ref string) (string, error) {
//				panic("mock out the RevParse method")
//			},
//		}
//
//		// use mockedGit in code that requires Git
//		// and then make assertions.
//
//	}
type MoqGit struct {
	// CheckoutFunc mocks the Checkout method.
	CheckoutFunc func(repoDir string, ref string) error

	// CloneFunc mocks the Clone method.
	CloneFunc func(repoURL string, targetDir string) error

	// FetchFunc mocks the Fetch method.
	FetchFunc func(repoDir string) error

	// RevParseFunc mocks the RevParse method.
	RevParseFunc func(repoDir string, ref string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checkout holds details about calls to the Checkout method.
		Checkout []struct {
			// RepoDir is the repoDir argument value.
			RepoDir string
			// Ref is the ref argument value.
			Ref string
		}
		// Clone holds details about calls to the Clone method.
		Clone []struct {
			// RepoURL is the repoURL argument value.
			RepoURL string
			// TargetDir is the targetDir argument value.
			TargetDir string
		}
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// RepoDir is the repoDir argument value.
			RepoDir string
		}
		// RevParse holds details about calls to the RevParse method.
		RevParse []struct {
			// RepoDir is the repoDir argument value.
			RepoDir string
			// Ref is the ref argument value.
			Ref string
		}
	}
	lockCheckout sync.RWMutex
	lockClone    sync.RWMutex
	lockFetch    sync.RWMutex
	lockRevParse sync.RWMutex
}

// Checkout calls CheckoutFunc.
func (mock *MoqGit) Checkout(repoDir string, ref string) error {
	if mock.CheckoutFunc == nil {
		panic("MoqGit.CheckoutFunc: method is nil but Git.Checkout was just called")
	}
	callInfo := struct {
		RepoDir string
		Ref     string
	}{
		RepoDir: repoDir,
		Ref:     ref,
	}
	mock.lockCheckout.Lock()
	mock.calls.Checkout = append(mock.calls.Checkout, callInfo)
	mock.lockCheckout.Unlock()
	return mock.CheckoutFunc(repoDir, ref)
}

// CheckoutCalls gets all the calls that were made to Checkout.
// Check the length with:
//
//	len(mockedGit.CheckoutCalls())
func (mock *MoqGit) CheckoutCalls() []struct {
	RepoDir string
	Ref     string
} {
	var calls []struct {
		RepoDir string
		Ref     string
	}
	mock.lockCheckout.RLock()
	calls = mock.calls.Checkout
	mock.lockCheckout.RUnlock()
	return calls
}

// Clone calls CloneFunc.
func (mock *MoqGit) Clone(repoURL string, targetDir string) error {
	if mock.CloneFunc == nil {
		panic("MoqGit.CloneFunc: method is nil but Git.Clone was just called")
	}
	callInfo := struct {
		RepoURL   string
		TargetDir string
	}{
		RepoURL:   repoURL,
		TargetDir: targetDir,
	}
	mock.lockClone.Lock()
	mock.calls.Clone = append(mock.calls.Clone, callInfo)
	mock.lockClone.Unlock()
	return mock.CloneFunc(repoURL, targetDir)
}

// CloneCalls gets all the calls that were made to Clone.
// Check the length with:
//
//	len(mockedGit.CloneCalls())
func (mock *MoqGit) CloneCalls() []struct {
	RepoURL   string
	TargetDir string
} {
	var calls []struct {
		RepoURL   string
		TargetDir string
	}
	mock.lockClone.RLock()
	calls = mock.calls.Clone
	mock.lockClone.RUnlock()
	return calls
}

// Fetch calls FetchFunc.
func (mock *MoqGit) Fetch(repoDir string) error {
	if mock.FetchFunc == nil {
		panic("MoqGit.FetchFunc: method is nil but Git.Fetch was just called")
	}
	callInfo := struct {
		RepoDir string
	}{
		RepoDir: repoDir,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(repoDir)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedGit.FetchCalls())
func (mock *MoqGit) FetchCalls() []struct {
	RepoDir string
} {
	var calls []struct {
		RepoDir string
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}

// RevParse calls RevParseFunc.
func (mock *MoqGit) RevParse(repoDir string, ref string) (string, error) {
	if mock.RevParseFunc == nil {
		panic("MoqGit.RevParseFunc: method is nil but Git.RevParse was just called")
	}
	callInfo := struct {
		RepoDir string
		Ref     string
	}{
		RepoDir: repoDir,
		Ref:     ref,
	}
	mock.lockRevParse.Lock()
	mock.calls.RevParse = append(mock.calls.RevParse, callInfo)
	mock.lockRevParse.Unlock()
	return mock.RevParseFunc(repoDir, ref)
}

// RevParseCalls gets all the calls that were made to RevParse.
// Check the length with:
//
//	len(mockedGit.RevParseCalls())
func (mock *MoqGit) RevParseCalls() []struct {
	RepoDir string
	Ref     string
} {
	var calls []struct {
		RepoDir string
		Ref     string
	}
	mock.lockRevParse.RLock()
	calls = mock.calls.RevParse
	mock.lockRevParse.RUnlock()
	return calls
}
