// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package workspace

import (
	"context"
	"sync"
)

// Ensure that MoqGit does implement Git.
// If this is not the case, regenerate this file with mockery.
var _ Git = &MoqGit{}

// MoqGit is a mock implementation of Git.
//
//	func TestSomethingThatUsesGit(t *testing.T) {
//
//		// make and configure a mocked Git
//		mockedGit := &MoqGit{
//			CheckoutFunc: func(ctx context.Context, repoDir string, ref string) error {
//				panic("mock out the Checkout method")
//			},
//			CloneFunc: func(ctx context.Context, repoURL string, targetDir string) error {
//				panic("mock out the Clone method")
//			},
//			FetchFunc: func(ctx context.Context, repoDir string) error {
//				panic("mock out the Fetch method")
//			},
//			RevParseFunc: func(ctx context.Context, repoDir string, ref string) (string, error) {
//				panic("mock out the RevParse method")
//			},
//			WorktreeAddFunc: func(ctx context.Context, repoDir string, ref string) (string, error) {
//				panic("mock out the WorktreeAdd method")
//			},
//			WorktreeRemoveFunc: func(ctx context.Context, worktreePath string) error {
//				panic("mock out the WorktreeRemove method")
//			},
//		}
//
//		// use mockedGit in code that requires Git
//		// and then make assertions.
//
//	}
type MoqGit struct {
	// CheckoutFunc mocks the Checkout method.
	CheckoutFunc func(ctx context.Context, repoDir string, ref string) error

	// CloneFunc mocks the Clone method.
	CloneFunc func(ctx context.Context, repoURL string, targetDir string) error

	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, repoDir string) error

	// RevParseFunc mocks the RevParse method.
	RevParseFunc func(ctx context.Context, repoDir string, ref string) (string, error)

	// WorktreeAddFunc mocks the WorktreeAdd method.
	WorktreeAddFunc func(ctx context.Context, repoDir string, ref string) (string, error)

	// WorktreeRemoveFunc mocks the WorktreeRemove method.
	WorktreeRemoveFunc func(ctx context.Context, worktreePath string) error

	// calls tracks calls to the methods.
	calls struct {
		// Checkout holds details about calls to the Checkout method.
		Checkout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoDir is the repoDir argument value.
			RepoDir string
			// Ref is the ref argument value.
			Ref string
		}
		// Clone holds details about calls to the Clone method.
		Clone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoURL is the repoURL argument value.
			RepoURL string
			// TargetDir is the targetDir argument value.
			TargetDir string
		}
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoDir is the repoDir argument value.
			RepoDir string
		}
		// RevParse holds details about calls to the RevParse method.
		RevParse []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoDir is the repoDir argument value.
			RepoDir string
			// Ref is the ref argument value.
			Ref string
		}
		// WorktreeAdd holds details about calls to the WorktreeAdd method.
		WorktreeAdd []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoDir is the repoDir argument value.
			RepoDir string
			// Ref is the ref argument value.
			Ref string
		}
		// WorktreeRemove holds details about calls to the WorktreeRemove method.
		WorktreeRemove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorktreePath is the worktreePath argument value.
			WorktreePath string
		}
	}
	lockCheckout       sync.RWMutex
	lockClone          sync.RWMutex
	lockFetch          sync.RWMutex
	lockRevParse       sync.RWMutex
	lockWorktreeAdd    sync.RWMutex
	lockWorktreeRemove sync.RWMutex
}

// Checkout calls CheckoutFunc.
func (mock *MoqGit) Checkout(ctx context.Context, repoDir string, ref string) error {
	if mock.CheckoutFunc == nil {
		panic("MoqGit.CheckoutFunc: method is nil but Git.Checkout was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoDir string
		Ref     string
	}{
		Ctx:     ctx,
		RepoDir: repoDir,
		Ref:     ref,
	}
	mock.lockCheckout.Lock()
	mock.calls.Checkout = append(mock.calls.Checkout, callInfo)
	mock.lockCheckout.Unlock()
	return mock.CheckoutFunc(ctx, repoDir, ref)
}

// CheckoutCalls gets all the calls that were made to Checkout.
// Check the length with:
//
//	len(mockedGit.CheckoutCalls())
func (mock *MoqGit) CheckoutCalls() []struct {
	Ctx     context.Context
	RepoDir string
	Ref     string
} {
	var calls []struct {
		Ctx     context.Context
		RepoDir string
		Ref     string
	}
	mock.lockCheckout.RLock()
	calls = mock.calls.Checkout
	mock.lockCheckout.RUnlock()
	return calls
}

// Clone calls CloneFunc.
func (mock *MoqGit) Clone(ctx context.Context, repoURL string, targetDir string) error {
	if mock.CloneFunc == nil {
		panic("MoqGit.CloneFunc: method is nil but Git.Clone was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		RepoURL   string
		TargetDir string
	}{
		Ctx:       ctx,
		RepoURL:   repoURL,
		TargetDir: targetDir,
	}
	mock.lockClone.Lock()
	mock.calls.Clone = append(mock.calls.Clone, callInfo)
	mock.lockClone.Unlock()
	return mock.CloneFunc(ctx, repoURL, targetDir)
}

// CloneCalls gets all the calls that were made to Clone.
// Check the length with:
//
//	len(mockedGit.CloneCalls())
func (mock *MoqGit) CloneCalls() []struct {
	Ctx       context.Context
	RepoURL   string
	TargetDir string
} {
	var calls []struct {
		Ctx       context.Context
		RepoURL   string
		TargetDir string
	}
	mock.lockClone.RLock()
	calls = mock.calls.Clone
	mock.lockClone.RUnlock()
	return calls
}

// Fetch calls FetchFunc.
func (mock *MoqGit) Fetch(ctx context.Context, repoDir string) error {
	if mock.FetchFunc == nil {
		panic("MoqGit.FetchFunc: method is nil but Git.Fetch was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoDir string
	}{
		Ctx:     ctx,
		RepoDir: repoDir,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, repoDir)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedGit.FetchCalls())
func (mock *MoqGit) FetchCalls() []struct {
	Ctx     context.Context
	RepoDir string
} {
	var calls []struct {
		Ctx     context.Context
		RepoDir string
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}

// RevParse calls RevParseFunc.
func (mock *MoqGit) RevParse(ctx context.Context, repoDir string, ref string) (string, error) {
	if mock.RevParseFunc == nil {
		panic("MoqGit.RevParseFunc: method is nil but Git.RevParse was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoDir string
		Ref     string
	}{
		Ctx:     ctx,
		RepoDir: repoDir,
		Ref:     ref,
	}
	mock.lockRevParse.Lock()
	mock.calls.RevParse = append(mock.calls.RevParse, callInfo)
	mock.lockRevParse.Unlock()
	return mock.RevParseFunc(ctx, repoDir, ref)
}

// RevParseCalls gets all the calls that were made to RevParse.
// Check the length with:
//
//	len(mockedGit.RevParseCalls())
func (mock *MoqGit) RevParseCalls() []struct {
	Ctx     context.Context
	RepoDir string
	Ref     string
} {
	var calls []struct {
		Ctx     context.Context
		RepoDir string
		Ref     string
	}
	mock.lockRevParse.RLock()
	calls = mock.calls.RevParse
	mock.lockRevParse.RUnlock()
	return calls
}

// WorktreeAdd calls WorktreeAddFunc.
func (mock *MoqGit) WorktreeAdd(ctx context.Context, repoDir string, ref string) (string, error) {
	if mock.WorktreeAddFunc == nil {
		panic("MoqGit.WorktreeAddFunc: method is nil but Git.WorktreeAdd was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoDir string
		Ref     string
	}{
		Ctx:     ctx,
		RepoDir: repoDir,
		Ref:     ref,
	}
	mock.lockWorktreeAdd.Lock()
	mock.calls.WorktreeAdd = append(mock.calls.WorktreeAdd, callInfo)
	mock.lockWorktreeAdd.Unlock()
	return mock.WorktreeAddFunc(ctx, repoDir, ref)
}

// WorktreeAddCalls gets all the calls that were made to WorktreeAdd.
// Check the length with:
//
//	len(mockedGit.WorktreeAddCalls())
func (mock *MoqGit) WorktreeAddCalls() []struct {
	Ctx     context.Context
	RepoDir string
	Ref     string
} {
	var calls []struct {
		Ctx     context.Context
		RepoDir string
		Ref     string
	}
	mock.lockWorktreeAdd.RLock()
	calls = mock.calls.WorktreeAdd
	mock.lockWorktreeAdd.RUnlock()
	return calls
}

// WorktreeRemove calls WorktreeRemoveFunc.
func (mock *MoqGit) WorktreeRemove(ctx context.Context, worktreePath string) error {
	if mock.WorktreeRemoveFunc == nil {
		panic("MoqGit.WorktreeRemoveFunc: method is nil but Git.WorktreeRemove was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		WorktreePath string
	}{
		Ctx:          ctx,
		WorktreePath: worktreePath,
	}
	mock.lockWorktreeRemove.Lock()
	mock.calls.WorktreeRemove = append(mock.calls.WorktreeRemove, callInfo)
	mock.lockWorktreeRemove.Unlock()
	return mock.WorktreeRemoveFunc(ctx, worktreePath)
}

// WorktreeRemoveCalls gets all the calls that were made to WorktreeRemove.
// Check the length with:
//
//	len(mockedGit.WorktreeRemoveCalls())
func (mock *MoqGit) WorktreeRemoveCalls() []struct {
	Ctx          context.Context
	WorktreePath string
} {
	var calls []struct {
		Ctx          context.Context
		WorktreePath string
	}
	mock.lockWorktreeRemove.RLock()
	calls = mock.calls.WorktreeRemove
	mock.lockWorktreeRemove.RUnlock()
	return calls
}
