// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package adapter

import (
	"context"
	"sync"
)

// Ensure that MoqDispatcher does implement Dispatcher.
// If this is not the case, regenerate this file with mockery.
var _ Dispatcher = &MoqDispatcher{}

// MoqDispatcher is a mock implementation of Dispatcher.
//
//	func TestSomethingThatUsesDispatcher(t *testing.T) {
//
//		// make and configure a mocked Dispatcher
//		mockedDispatcher := &MoqDispatcher{
//			ApplyFunc: func(ctx context.Context, framework string, req *ApplyRequest) (*ApplyResponse, error) {
//				panic("mock out the Apply method")
//			},
//		}
//
//		// use mockedDispatcher in code that requires Dispatcher
//		// and then make assertions.
//
//	}
type MoqDispatcher struct {
	// ApplyFunc mocks the Apply method.
	ApplyFunc func(ctx context.Context, framework string, req *ApplyRequest) (*ApplyResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Apply holds details about calls to the Apply method.
		Apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Framework is the framework argument value.
			Framework string
			// Req is the req argument value.
			Req *ApplyRequest
		}
	}
	lockApply sync.RWMutex
}

// Apply calls ApplyFunc.
func (mock *MoqDispatcher) Apply(ctx context.Context, framework string, req *ApplyRequest) (*ApplyResponse, error) {
	if mock.ApplyFunc == nil {
		panic("MoqDispatcher.ApplyFunc: method is nil but Dispatcher.Apply was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Framework string
		Req       *ApplyRequest
	}{
		Ctx:       ctx,
		Framework: framework,
		Req:       req,
	}
	mock.lockApply.Lock()
	mock.calls.Apply = append(mock.calls.Apply, callInfo)
	mock.lockApply.Unlock()
	return mock.ApplyFunc(ctx, framework, req)
}

// ApplyCalls gets all the calls that were made to Apply.
// Check the length with:
//
//	len(mockedDispatcher.ApplyCalls())
func (mock *MoqDispatcher) ApplyCalls() []struct {
	Ctx       context.Context
	Framework string
	Req       *ApplyRequest
} {
	var calls []struct {
		Ctx       context.Context
		Framework string
		Req       *ApplyRequest
	}
	mock.lockApply.RLock()
	calls = mock.calls.Apply
	mock.lockApply.RUnlock()
	return calls
}
