// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package state

import (
	"context"
	"sync"
)

// Ensure that MoqBlockStore does implement BlockStore.
// If this is not the case, regenerate this file with mockery.
var _ BlockStore = &MoqBlockStore{}

// MoqBlockStore is a mock implementation of BlockStore.
//
//	func TestSomethingThatUsesBlockStore(t *testing.T) {
//
//		// make and configure a mocked BlockStore
//		mockedBlockStore := &MoqBlockStore{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			DeleteByPathsFunc: func(ctx context.Context, paths []string) error {
//				panic("mock out the DeleteByPaths method")
//			},
//			DeleteBySubscriptionFunc: func(ctx context.Context, subscription string) error {
//				panic("mock out the DeleteBySubscription method")
//			},
//			QueryByPathFunc: func(ctx context.Context, path string) (*Record, error) {
//				panic("mock out the QueryByPath method")
//			},
//			QueryBySubscriptionFunc: func(ctx context.Context, subscription string) ([]Record, error) {
//				panic("mock out the QueryBySubscription method")
//			},
//			QueryBySubscriptionAgentFunc: func(ctx context.Context, subscription string, agent string) ([]Record, error) {
//				panic("mock out the QueryBySubscriptionAgent method")
//			},
//			RecordBatchFunc: func(ctx context.Context, records []Record) error {
//				panic("mock out the RecordBatch method")
//			},
//		}
//
//		// use mockedBlockStore in code that requires BlockStore
//		// and then make assertions.
//
//	}
type MoqBlockStore struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// DeleteByPathsFunc mocks the DeleteByPaths method.
	DeleteByPathsFunc func(ctx context.Context, paths []string) error

	// DeleteBySubscriptionFunc mocks the DeleteBySubscription method.
	DeleteBySubscriptionFunc func(ctx context.Context, subscription string) error

	// QueryByPathFunc mocks the QueryByPath method.
	QueryByPathFunc func(ctx context.Context, path string) (*Record, error)

	// QueryBySubscriptionFunc mocks the QueryBySubscription method.
	QueryBySubscriptionFunc func(ctx context.Context, subscription string) ([]Record, error)

	// QueryBySubscriptionAgentFunc mocks the QueryBySubscriptionAgent method.
	QueryBySubscriptionAgentFunc func(ctx context.Context, subscription string, agent string) ([]Record, error)

	// RecordBatchFunc mocks the RecordBatch method.
	RecordBatchFunc func(ctx context.Context, records []Record) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// DeleteByPaths holds details about calls to the DeleteByPaths method.
		DeleteByPaths []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Paths is the paths argument value.
			Paths []string
		}
		// DeleteBySubscription holds details about calls to the DeleteBySubscription method.
		DeleteBySubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Subscription is the subscription argument value.
			Subscription string
		}
		// QueryByPath holds details about calls to the QueryByPath method.
		QueryByPath []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
		// QueryBySubscription holds details about calls to the QueryBySubscription method.
		QueryBySubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Subscription is the subscription argument value.
			Subscription string
		}
		// QueryBySubscriptionAgent holds details about calls to the QueryBySubscriptionAgent method.
		QueryBySubscriptionAgent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Subscription is the subscription argument value.
			Subscription string
			// Agent is the agent argument value.
			Agent string
		}
		// RecordBatch holds details about calls to the RecordBatch method.
		RecordBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Records is the records argument value.
			Records []Record
		}
	}
	lockClose                    sync.RWMutex
	lockDeleteByPaths            sync.RWMutex
	lockDeleteBySubscription     sync.RWMutex
	lockQueryByPath              sync.RWMutex
	lockQueryBySubscription      sync.RWMutex
	lockQueryBySubscriptionAgent sync.RWMutex
	lockRecordBatch              sync.RWMutex
}

// Close calls CloseFunc.
func (mock *MoqBlockStore) Close() error {
	if mock.CloseFunc == nil {
		panic("MoqBlockStore.CloseFunc: method is nil but BlockStore.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedBlockStore.CloseCalls())
func (mock *MoqBlockStore) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// DeleteByPaths calls DeleteByPathsFunc.
func (mock *MoqBlockStore) DeleteByPaths(ctx context.Context, paths []string) error {
	if mock.DeleteByPathsFunc == nil {
		panic("MoqBlockStore.DeleteByPathsFunc: method is nil but BlockStore.DeleteByPaths was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Paths []string
	}{
		Ctx:   ctx,
		Paths: paths,
	}
	mock.lockDeleteByPaths.Lock()
	mock.calls.DeleteByPaths = append(mock.calls.DeleteByPaths, callInfo)
	mock.lockDeleteByPaths.Unlock()
	return mock.DeleteByPathsFunc(ctx, paths)
}

// DeleteByPathsCalls gets all the calls that were made to DeleteByPaths.
// Check the length with:
//
//	len(mockedBlockStore.DeleteByPathsCalls())
func (mock *MoqBlockStore) DeleteByPathsCalls() []struct {
	Ctx   context.Context
	Paths []string
} {
	var calls []struct {
		Ctx   context.Context
		Paths []string
	}
	mock.lockDeleteByPaths.RLock()
	calls = mock.calls.DeleteByPaths
	mock.lockDeleteByPaths.RUnlock()
	return calls
}

// DeleteBySubscription calls DeleteBySubscriptionFunc.
func (mock *MoqBlockStore) DeleteBySubscription(ctx context.Context, subscription string) error {
	if mock.DeleteBySubscriptionFunc == nil {
		panic("MoqBlockStore.DeleteBySubscriptionFunc: method is nil but BlockStore.DeleteBySubscription was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Subscription string
	}{
		Ctx:          ctx,
		Subscription: subscription,
	}
	mock.lockDeleteBySubscription.Lock()
	mock.calls.DeleteBySubscription = append(mock.calls.DeleteBySubscription, callInfo)
	mock.lockDeleteBySubscription.Unlock()
	return mock.DeleteBySubscriptionFunc(ctx, subscription)
}

// DeleteBySubscriptionCalls gets all the calls that were made to DeleteBySubscription.
// Check the length with:
//
//	len(mockedBlockStore.DeleteBySubscriptionCalls())
func (mock *MoqBlockStore) DeleteBySubscriptionCalls() []struct {
	Ctx          context.Context
	Subscription string
} {
	var calls []struct {
		Ctx          context.Context
		Subscription string
	}
	mock.lockDeleteBySubscription.RLock()
	calls = mock.calls.DeleteBySubscription
	mock.lockDeleteBySubscription.RUnlock()
	return calls
}

// QueryByPath calls QueryByPathFunc.
func (mock *MoqBlockStore) QueryByPath(ctx context.Context, path string) (*Record, error) {
	if mock.QueryByPathFunc == nil {
		panic("MoqBlockStore.QueryByPathFunc: method is nil but BlockStore.QueryByPath was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockQueryByPath.Lock()
	mock.calls.QueryByPath = append(mock.calls.QueryByPath, callInfo)
	mock.lockQueryByPath.Unlock()
	return mock.QueryByPathFunc(ctx, path)
}

// QueryByPathCalls gets all the calls that were made to QueryByPath.
// Check the length with:
//
//	len(mockedBlockStore.QueryByPathCalls())
func (mock *MoqBlockStore) QueryByPathCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockQueryByPath.RLock()
	calls = mock.calls.QueryByPath
	mock.lockQueryByPath.RUnlock()
	return calls
}

// QueryBySubscription calls QueryBySubscriptionFunc.
func (mock *MoqBlockStore) QueryBySubscription(ctx context.Context, subscription string) ([]Record, error) {
	if mock.QueryBySubscriptionFunc == nil {
		panic("MoqBlockStore.QueryBySubscriptionFunc: method is nil but BlockStore.QueryBySubscription was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Subscription string
	}{
		Ctx:          ctx,
		Subscription: subscription,
	}
	mock.lockQueryBySubscription.Lock()
	mock.calls.QueryBySubscription = append(mock.calls.QueryBySubscription, callInfo)
	mock.lockQueryBySubscription.Unlock()
	return mock.QueryBySubscriptionFunc(ctx, subscription)
}

// QueryBySubscriptionCalls gets all the calls that were made to QueryBySubscription.
// Check the length with:
//
//	len(mockedBlockStore.QueryBySubscriptionCalls())
func (mock *MoqBlockStore) QueryBySubscriptionCalls() []struct {
	Ctx          context.Context
	Subscription string
} {
	var calls []struct {
		Ctx          context.Context
		Subscription string
	}
	mock.lockQueryBySubscription.RLock()
	calls = mock.calls.QueryBySubscription
	mock.lockQueryBySubscription.RUnlock()
	return calls
}

// QueryBySubscriptionAgent calls QueryBySubscriptionAgentFunc.
func (mock *MoqBlockStore) QueryBySubscriptionAgent(ctx context.Context, subscription string, agent string) ([]Record, error) {
	if mock.QueryBySubscriptionAgentFunc == nil {
		panic("MoqBlockStore.QueryBySubscriptionAgentFunc: method is nil but BlockStore.QueryBySubscriptionAgent was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Subscription string
		Agent        string
	}{
		Ctx:          ctx,
		Subscription: subscription,
		Agent:        agent,
	}
	mock.lockQueryBySubscriptionAgent.Lock()
	mock.calls.QueryBySubscriptionAgent = append(mock.calls.QueryBySubscriptionAgent, callInfo)
	mock.lockQueryBySubscriptionAgent.Unlock()
	return mock.QueryBySubscriptionAgentFunc(ctx, subscription, agent)
}

// QueryBySubscriptionAgentCalls gets all the calls that were made to QueryBySubscriptionAgent.
// Check the length with:
//
//	len(mockedBlockStore.QueryBySubscriptionAgentCalls())
func (mock *MoqBlockStore) QueryBySubscriptionAgentCalls() []struct {
	Ctx          context.Context
	Subscription string
	Agent        string
} {
	var calls []struct {
		Ctx          context.Context
		Subscription string
		Agent        string
	}
	mock.lockQueryBySubscriptionAgent.RLock()
	calls = mock.calls.QueryBySubscriptionAgent
	mock.lockQueryBySubscriptionAgent.RUnlock()
	return calls
}

// RecordBatch calls RecordBatchFunc.
func (mock *MoqBlockStore) RecordBatch(ctx context.Context, records []Record) error {
	if mock.RecordBatchFunc == nil {
		panic("MoqBlockStore.RecordBatchFunc: method is nil but BlockStore.RecordBatch was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Records []Record
	}{
		Ctx:     ctx,
		Records: records,
	}
	mock.lockRecordBatch.Lock()
	mock.calls.RecordBatch = append(mock.calls.RecordBatch, callInfo)
	mock.lockRecordBatch.Unlock()
	return mock.RecordBatchFunc(ctx, records)
}

// RecordBatchCalls gets all the calls that were made to RecordBatch.
// Check the length with:
//
//	len(mockedBlockStore.RecordBatchCalls())
func (mock *MoqBlockStore) RecordBatchCalls() []struct {
	Ctx     context.Context
	Records []Record
} {
	var calls []struct {
		Ctx     context.Context
		Records []Record
	}
	mock.lockRecordBatch.RLock()
	calls = mock.calls.RecordBatch
	mock.lockRecordBatch.RUnlock()
	return calls
}
