// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package osmanager

import (
	"context"
	"sync"
)

// Ensure that MoqOsManager does implement OsManager.
// If this is not the case, regenerate this file with mockery.
var _ OsManager = &MoqOsManager{}

// MoqOsManager is a mock implementation of OsManager.
//
//	func TestSomethingThatUsesOsManager(t *testing.T) {
//
//		// make and configure a mocked OsManager
//		mockedOsManager := &MoqOsManager{
//			GetConfigDirFunc: func() (string, error) {
//				panic("mock out the GetConfigDir method")
//			},
//			GetCurrentUsernameFunc: func() (string, error) {
//				panic("mock out the GetCurrentUsername method")
//			},
//			GetHomeDirFunc: func() (string, error) {
//				panic("mock out the GetHomeDir method")
//			},
//			GetProgramPathFunc: func(program string) (string, error) {
//				panic("mock out the GetProgramPath method")
//			},
//			GetProgramVersionFunc: func(ctx context.Context, program string, versionExtractor VersionExtractor, queryArgs ...string) (string, error) {
//				panic("mock out the GetProgramVersion method")
//			},
//			GetenvFunc: func(key string) string {
//				panic("mock out the Getenv method")
//			},
//			ProgramExistsFunc: func(program string) (bool, error) {
//				panic("mock out the ProgramExists method")
//			},
//		}
//
//		// use mockedOsManager in code that requires OsManager
//		// and then make assertions.
//
//	}
type MoqOsManager struct {
	// GetConfigDirFunc mocks the GetConfigDir method.
	GetConfigDirFunc func() (string, error)

	// GetCurrentUsernameFunc mocks the GetCurrentUsername method.
	GetCurrentUsernameFunc func() (string, error)

	// GetHomeDirFunc mocks the GetHomeDir method.
	GetHomeDirFunc func() (string, error)

	// GetProgramPathFunc mocks the GetProgramPath method.
	GetProgramPathFunc func(program string) (string, error)

	// GetProgramVersionFunc mocks the GetProgramVersion method.
	GetProgramVersionFunc func(ctx context.Context, program string, versionExtractor VersionExtractor, queryArgs ...string) (string, error)

	// GetenvFunc mocks the Getenv method.
	GetenvFunc func(key string) string

	// ProgramExistsFunc mocks the ProgramExists method.
	ProgramExistsFunc func(program string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetConfigDir holds details about calls to the GetConfigDir method.
		GetConfigDir []struct {
		}
		// GetCurrentUsername holds details about calls to the GetCurrentUsername method.
		GetCurrentUsername []struct {
		}
		// GetHomeDir holds details about calls to the GetHomeDir method.
		GetHomeDir []struct {
		}
		// GetProgramPath holds details about calls to the GetProgramPath method.
		GetProgramPath []struct {
			// Program is the program argument value.
			Program string
		}
		// GetProgramVersion holds details about calls to the GetProgramVersion method.
		GetProgramVersion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Program is the program argument value.
			Program string
			// VersionExtractor is the versionExtractor argument value.
			VersionExtractor VersionExtractor
			// QueryArgs is the queryArgs argument value.
			QueryArgs []string
		}
		// Getenv holds details about calls to the Getenv method.
		Getenv []struct {
			// Key is the key argument value.
			Key string
		}
		// ProgramExists holds details about calls to the ProgramExists method.
		ProgramExists []struct {
			// Program is the program argument value.
			Program string
		}
	}
	lockGetConfigDir       sync.RWMutex
	lockGetCurrentUsername sync.RWMutex
	lockGetHomeDir         sync.RWMutex
	lockGetProgramPath     sync.RWMutex
	lockGetProgramVersion  sync.RWMutex
	lockGetenv             sync.RWMutex
	lockProgramExists      sync.RWMutex
}

// GetConfigDir calls GetConfigDirFunc.
func (mock *MoqOsManager) GetConfigDir() (string, error) {
	if mock.GetConfigDirFunc == nil {
		panic("MoqOsManager.GetConfigDirFunc: method is nil but OsManager.GetConfigDir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetConfigDir.Lock()
	mock.calls.GetConfigDir = append(mock.calls.GetConfigDir, callInfo)
	mock.lockGetConfigDir.Unlock()
	return mock.GetConfigDirFunc()
}

// GetConfigDirCalls gets all the calls that were made to GetConfigDir.
// Check the length with:
//
//	len(mockedOsManager.GetConfigDirCalls())
func (mock *MoqOsManager) GetConfigDirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetConfigDir.RLock()
	calls = mock.calls.GetConfigDir
	mock.lockGetConfigDir.RUnlock()
	return calls
}

// GetCurrentUsername calls GetCurrentUsernameFunc.
func (mock *MoqOsManager) GetCurrentUsername() (string, error) {
	if mock.GetCurrentUsernameFunc == nil {
		panic("MoqOsManager.GetCurrentUsernameFunc: method is nil but OsManager.GetCurrentUsername was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetCurrentUsername.Lock()
	mock.calls.GetCurrentUsername = append(mock.calls.GetCurrentUsername, callInfo)
	mock.lockGetCurrentUsername.Unlock()
	return mock.GetCurrentUsernameFunc()
}

// GetCurrentUsernameCalls gets all the calls that were made to GetCurrentUsername.
// Check the length with:
//
//	len(mockedOsManager.GetCurrentUsernameCalls())
func (mock *MoqOsManager) GetCurrentUsernameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetCurrentUsername.RLock()
	calls = mock.calls.GetCurrentUsername
	mock.lockGetCurrentUsername.RUnlock()
	return calls
}

// GetHomeDir calls GetHomeDirFunc.
func (mock *MoqOsManager) GetHomeDir() (string, error) {
	if mock.GetHomeDirFunc == nil {
		panic("MoqOsManager.GetHomeDirFunc: method is nil but OsManager.GetHomeDir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetHomeDir.Lock()
	mock.calls.GetHomeDir = append(mock.calls.GetHomeDir, callInfo)
	mock.lockGetHomeDir.Unlock()
	return mock.GetHomeDirFunc()
}

// GetHomeDirCalls gets all the calls that were made to GetHomeDir.
// Check the length with:
//
//	len(mockedOsManager.GetHomeDirCalls())
func (mock *MoqOsManager) GetHomeDirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetHomeDir.RLock()
	calls = mock.calls.GetHomeDir
	mock.lockGetHomeDir.RUnlock()
	return calls
}

// GetProgramPath calls GetProgramPathFunc.
func (mock *MoqOsManager) GetProgramPath(program string) (string, error) {
	if mock.GetProgramPathFunc == nil {
		panic("MoqOsManager.GetProgramPathFunc: method is nil but OsManager.GetProgramPath was just called")
	}
	callInfo := struct {
		Program string
	}{
		Program: program,
	}
	mock.lockGetProgramPath.Lock()
	mock.calls.GetProgramPath = append(mock.calls.GetProgramPath, callInfo)
	mock.lockGetProgramPath.Unlock()
	return mock.GetProgramPathFunc(program)
}

// GetProgramPathCalls gets all the calls that were made to GetProgramPath.
// Check the length with:
//
//	len(mockedOsManager.GetProgramPathCalls())
func (mock *MoqOsManager) GetProgramPathCalls() []struct {
	Program string
} {
	var calls []struct {
		Program string
	}
	mock.lockGetProgramPath.RLock()
	calls = mock.calls.GetProgramPath
	mock.lockGetProgramPath.RUnlock()
	return calls
}

// GetProgramVersion calls GetProgramVersionFunc.
func (mock *MoqOsManager) GetProgramVersion(ctx context.Context, program string, versionExtractor VersionExtractor, queryArgs ...string) (string, error) {
	if mock.GetProgramVersionFunc == nil {
		panic("MoqOsManager.GetProgramVersionFunc: method is nil but OsManager.GetProgramVersion was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		Program          string
		VersionExtractor VersionExtractor
		QueryArgs        []string
	}{
		Ctx:              ctx,
		Program:          program,
		VersionExtractor: versionExtractor,
		QueryArgs:        queryArgs,
	}
	mock.lockGetProgramVersion.Lock()
	mock.calls.GetProgramVersion = append(mock.calls.GetProgramVersion, callInfo)
	mock.lockGetProgramVersion.Unlock()
	return mock.GetProgramVersionFunc(ctx, program, versionExtractor, queryArgs...)
}

// GetProgramVersionCalls gets all the calls that were made to GetProgramVersion.
// Check the length with:
//
//	len(mockedOsManager.GetProgramVersionCalls())
func (mock *MoqOsManager) GetProgramVersionCalls() []struct {
	Ctx              context.Context
	Program          string
	VersionExtractor VersionExtractor
	QueryArgs        []string
} {
	var calls []struct {
		Ctx              context.Context
		Program          string
		VersionExtractor VersionExtractor
		QueryArgs        []string
	}
	mock.lockGetProgramVersion.RLock()
	calls = mock.calls.GetProgramVersion
	mock.lockGetProgramVersion.RUnlock()
	return calls
}

// Getenv calls GetenvFunc.
func (mock *MoqOsManager) Getenv(key string) string {
	if mock.GetenvFunc == nil {
		panic("MoqOsManager.GetenvFunc: method is nil but OsManager.Getenv was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGetenv.Lock()
	mock.calls.Getenv = append(mock.calls.Getenv, callInfo)
	mock.lockGetenv.Unlock()
	return mock.GetenvFunc(key)
}

// GetenvCalls gets all the calls that were made to Getenv.
// Check the length with:
//
//	len(mockedOsManager.GetenvCalls())
func (mock *MoqOsManager) GetenvCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGetenv.RLock()
	calls = mock.calls.Getenv
	mock.lockGetenv.RUnlock()
	return calls
}

// ProgramExists calls ProgramExistsFunc.
func (mock *MoqOsManager) ProgramExists(program string) (bool, error) {
	if mock.ProgramExistsFunc == nil {
		panic("MoqOsManager.ProgramExistsFunc: method is nil but OsManager.ProgramExists was just called")
	}
	callInfo := struct {
		Program string
	}{
		Program: program,
	}
	mock.lockProgramExists.Lock()
	mock.calls.ProgramExists = append(mock.calls.ProgramExists, callInfo)
	mock.lockProgramExists.Unlock()
	return mock.ProgramExistsFunc(program)
}

// ProgramExistsCalls gets all the calls that were made to ProgramExists.
// Check the length with:
//
//	len(mockedOsManager.ProgramExistsCalls())
func (mock *MoqOsManager) ProgramExistsCalls() []struct {
	Program string
} {
	var calls []struct {
		Program string
	}
	mock.lockProgramExists.RLock()
	calls = mock.calls.ProgramExists
	mock.lockProgramExists.RUnlock()
	return calls
}
