// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package osmanager

import (
	"context"
	"sync"
)

// Ensure that MoqProgramQuery does implement ProgramQuery.
// If this is not the case, regenerate this file with mockery.
var _ ProgramQuery = &MoqProgramQuery{}

// MoqProgramQuery is a mock implementation of ProgramQuery.
//
//	func TestSomethingThatUsesProgramQuery(t *testing.T) {
//
//		// make and configure a mocked ProgramQuery
//		mockedProgramQuery := &MoqProgramQuery{
//			FindProgramsByPrefixFunc: func(prefix string) ([]string, error) {
//				panic("mock out the FindProgramsByPrefix method")
//			},
//			GetProgramPathFunc: func(program string) (string, error) {
//				panic("mock out the GetProgramPath method")
//			},
//			GetProgramVersionFunc: func(ctx context.Context, program string, versionExtractor VersionExtractor, queryArgs ...string) (string, error) {
//				panic("mock out the GetProgramVersion method")
//			},
//			ProgramExistsFunc: func(program string) (bool, error) {
//				panic("mock out the ProgramExists method")
//			},
//		}
//
//		// use mockedProgramQuery in code that requires ProgramQuery
//		// and then make assertions.
//
//	}
type MoqProgramQuery struct {
	// FindProgramsByPrefixFunc mocks the FindProgramsByPrefix method.
	FindProgramsByPrefixFunc func(prefix string) ([]string, error)

	// GetProgramPathFunc mocks the GetProgramPath method.
	GetProgramPathFunc func(program string) (string, error)

	// GetProgramVersionFunc mocks the GetProgramVersion method.
	GetProgramVersionFunc func(ctx context.Context, program string, versionExtractor VersionExtractor, queryArgs ...string) (string, error)

	// ProgramExistsFunc mocks the ProgramExists method.
	ProgramExistsFunc func(program string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindProgramsByPrefix holds details about calls to the FindProgramsByPrefix method.
		FindProgramsByPrefix []struct {
			// Prefix is the prefix argument value.
			Prefix string
		}
		// GetProgramPath holds details about calls to the GetProgramPath method.
		GetProgramPath []struct {
			// Program is the program argument value.
			Program string
		}
		// GetProgramVersion holds details about calls to the GetProgramVersion method.
		GetProgramVersion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Program is the program argument value.
			Program string
			// VersionExtractor is the versionExtractor argument value.
			VersionExtractor VersionExtractor
			// QueryArgs is the queryArgs argument value.
			QueryArgs []string
		}
		// ProgramExists holds details about calls to the ProgramExists method.
		ProgramExists []struct {
			// Program is the program argument value.
			Program string
		}
	}
	lockFindProgramsByPrefix sync.RWMutex
	lockGetProgramPath       sync.RWMutex
	lockGetProgramVersion    sync.RWMutex
	lockProgramExists        sync.RWMutex
}

// FindProgramsByPrefix calls FindProgramsByPrefixFunc.
func (mock *MoqProgramQuery) FindProgramsByPrefix(prefix string) ([]string, error) {
	if mock.FindProgramsByPrefixFunc == nil {
		panic("MoqProgramQuery.FindProgramsByPrefixFunc: method is nil but ProgramQuery.FindProgramsByPrefix was just called")
	}
	callInfo := struct {
		Prefix string
	}{
		Prefix: prefix,
	}
	mock.lockFindProgramsByPrefix.Lock()
	mock.calls.FindProgramsByPrefix = append(mock.calls.FindProgramsByPrefix, callInfo)
	mock.lockFindProgramsByPrefix.Unlock()
	return mock.FindProgramsByPrefixFunc(prefix)
}

// FindProgramsByPrefixCalls gets all the calls that were made to FindProgramsByPrefix.
// Check the length with:
//
//	len(mockedProgramQuery.FindProgramsByPrefixCalls())
func (mock *MoqProgramQuery) FindProgramsByPrefixCalls() []struct {
	Prefix string
} {
	var calls []struct {
		Prefix string
	}
	mock.lockFindProgramsByPrefix.RLock()
	calls = mock.calls.FindProgramsByPrefix
	mock.lockFindProgramsByPrefix.RUnlock()
	return calls
}

// GetProgramPath calls GetProgramPathFunc.
func (mock *MoqProgramQuery) GetProgramPath(program string) (string, error) {
	if mock.GetProgramPathFunc == nil {
		panic("MoqProgramQuery.GetProgramPathFunc: method is nil but ProgramQuery.GetProgramPath was just called")
	}
	callInfo := struct {
		Program string
	}{
		Program: program,
	}
	mock.lockGetProgramPath.Lock()
	mock.calls.GetProgramPath = append(mock.calls.GetProgramPath, callInfo)
	mock.lockGetProgramPath.Unlock()
	return mock.GetProgramPathFunc(program)
}

// GetProgramPathCalls gets all the calls that were made to GetProgramPath.
// Check the length with:
//
//	len(mockedProgramQuery.GetProgramPathCalls())
func (mock *MoqProgramQuery) GetProgramPathCalls() []struct {
	Program string
} {
	var calls []struct {
		Program string
	}
	mock.lockGetProgramPath.RLock()
	calls = mock.calls.GetProgramPath
	mock.lockGetProgramPath.RUnlock()
	return calls
}

// GetProgramVersion calls GetProgramVersionFunc.
func (mock *MoqProgramQuery) GetProgramVersion(ctx context.Context, program string, versionExtractor VersionExtractor, queryArgs ...string) (string, error) {
	if mock.GetProgramVersionFunc == nil {
		panic("MoqProgramQuery.GetProgramVersionFunc: method is nil but ProgramQuery.GetProgramVersion was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		Program          string
		VersionExtractor VersionExtractor
		QueryArgs        []string
	}{
		Ctx:              ctx,
		Program:          program,
		VersionExtractor: versionExtractor,
		QueryArgs:        queryArgs,
	}
	mock.lockGetProgramVersion.Lock()
	mock.calls.GetProgramVersion = append(mock.calls.GetProgramVersion, callInfo)
	mock.lockGetProgramVersion.Unlock()
	return mock.GetProgramVersionFunc(ctx, program, versionExtractor, queryArgs...)
}

// GetProgramVersionCalls gets all the calls that were made to GetProgramVersion.
// Check the length with:
//
//	len(mockedProgramQuery.GetProgramVersionCalls())
func (mock *MoqProgramQuery) GetProgramVersionCalls() []struct {
	Ctx              context.Context
	Program          string
	VersionExtractor VersionExtractor
	QueryArgs        []string
} {
	var calls []struct {
		Ctx              context.Context
		Program          string
		VersionExtractor VersionExtractor
		QueryArgs        []string
	}
	mock.lockGetProgramVersion.RLock()
	calls = mock.calls.GetProgramVersion
	mock.lockGetProgramVersion.RUnlock()
	return calls
}

// ProgramExists calls ProgramExistsFunc.
func (mock *MoqProgramQuery) ProgramExists(program string) (bool, error) {
	if mock.ProgramExistsFunc == nil {
		panic("MoqProgramQuery.ProgramExistsFunc: method is nil but ProgramQuery.ProgramExists was just called")
	}
	callInfo := struct {
		Program string
	}{
		Program: program,
	}
	mock.lockProgramExists.Lock()
	mock.calls.ProgramExists = append(mock.calls.ProgramExists, callInfo)
	mock.lockProgramExists.Unlock()
	return mock.ProgramExistsFunc(program)
}

// ProgramExistsCalls gets all the calls that were made to ProgramExists.
// Check the length with:
//
//	len(mockedProgramQuery.ProgramExistsCalls())
func (mock *MoqProgramQuery) ProgramExistsCalls() []struct {
	Program string
} {
	var calls []struct {
		Program string
	}
	mock.lockProgramExists.RLock()
	calls = mock.calls.ProgramExists
	mock.lockProgramExists.RUnlock()
	return calls
}
