// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package osmanager

import (
	"sync"
)

// Ensure that MoqUserManager does implement UserManager.
// If this is not the case, regenerate this file with mockery.
var _ UserManager = &MoqUserManager{}

// MoqUserManager is a mock implementation of UserManager.
//
//	func TestSomethingThatUsesUserManager(t *testing.T) {
//
//		// make and configure a mocked UserManager
//		mockedUserManager := &MoqUserManager{
//			GetConfigDirFunc: func() (string, error) {
//				panic("mock out the GetConfigDir method")
//			},
//			GetCurrentUsernameFunc: func() (string, error) {
//				panic("mock out the GetCurrentUsername method")
//			},
//			GetHomeDirFunc: func() (string, error) {
//				panic("mock out the GetHomeDir method")
//			},
//		}
//
//		// use mockedUserManager in code that requires UserManager
//		// and then make assertions.
//
//	}
type MoqUserManager struct {
	// GetConfigDirFunc mocks the GetConfigDir method.
	GetConfigDirFunc func() (string, error)

	// GetCurrentUsernameFunc mocks the GetCurrentUsername method.
	GetCurrentUsernameFunc func() (string, error)

	// GetHomeDirFunc mocks the GetHomeDir method.
	GetHomeDirFunc func() (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetConfigDir holds details about calls to the GetConfigDir method.
		GetConfigDir []struct {
		}
		// GetCurrentUsername holds details about calls to the GetCurrentUsername method.
		GetCurrentUsername []struct {
		}
		// GetHomeDir holds details about calls to the GetHomeDir method.
		GetHomeDir []struct {
		}
	}
	lockGetConfigDir       sync.RWMutex
	lockGetCurrentUsername sync.RWMutex
	lockGetHomeDir         sync.RWMutex
}

// GetConfigDir calls GetConfigDirFunc.
func (mock *MoqUserManager) GetConfigDir() (string, error) {
	if mock.GetConfigDirFunc == nil {
		panic("MoqUserManager.GetConfigDirFunc: method is nil but UserManager.GetConfigDir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetConfigDir.Lock()
	mock.calls.GetConfigDir = append(mock.calls.GetConfigDir, callInfo)
	mock.lockGetConfigDir.Unlock()
	return mock.GetConfigDirFunc()
}

// GetConfigDirCalls gets all the calls that were made to GetConfigDir.
// Check the length with:
//
//	len(mockedUserManager.GetConfigDirCalls())
func (mock *MoqUserManager) GetConfigDirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetConfigDir.RLock()
	calls = mock.calls.GetConfigDir
	mock.lockGetConfigDir.RUnlock()
	return calls
}

// GetCurrentUsername calls GetCurrentUsernameFunc.
func (mock *MoqUserManager) GetCurrentUsername() (string, error) {
	if mock.GetCurrentUsernameFunc == nil {
		panic("MoqUserManager.GetCurrentUsernameFunc: method is nil but UserManager.GetCurrentUsername was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetCurrentUsername.Lock()
	mock.calls.GetCurrentUsername = append(mock.calls.GetCurrentUsername, callInfo)
	mock.lockGetCurrentUsername.Unlock()
	return mock.GetCurrentUsernameFunc()
}

// GetCurrentUsernameCalls gets all the calls that were made to GetCurrentUsername.
// Check the length with:
//
//	len(mockedUserManager.GetCurrentUsernameCalls())
func (mock *MoqUserManager) GetCurrentUsernameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetCurrentUsername.RLock()
	calls = mock.calls.GetCurrentUsername
	mock.lockGetCurrentUsername.RUnlock()
	return calls
}

// GetHomeDir calls GetHomeDirFunc.
func (mock *MoqUserManager) GetHomeDir() (string, error) {
	if mock.GetHomeDirFunc == nil {
		panic("MoqUserManager.GetHomeDirFunc: method is nil but UserManager.GetHomeDir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetHomeDir.Lock()
	mock.calls.GetHomeDir = append(mock.calls.GetHomeDir, callInfo)
	mock.lockGetHomeDir.Unlock()
	return mock.GetHomeDirFunc()
}

// GetHomeDirCalls gets all the calls that were made to GetHomeDir.
// Check the length with:
//
//	len(mockedUserManager.GetHomeDirCalls())
func (mock *MoqUserManager) GetHomeDirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetHomeDir.RLock()
	calls = mock.calls.GetHomeDir
	mock.lockGetHomeDir.RUnlock()
	return calls
}
