// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package utils

import (
	"context"
	"sync"
)

// Ensure that MoqLocker does implement Locker.
// If this is not the case, regenerate this file with mockery.
var _ Locker = &MoqLocker{}

// MoqLocker is a mock implementation of Locker.
//
//	func TestSomethingThatUsesLocker(t *testing.T) {
//
//		// make and configure a mocked Locker
//		mockedLocker := &MoqLocker{
//			WithLockFunc: func(ctx context.Context, path string, fn func() error) error {
//				panic("mock out the WithLock method")
//			},
//		}
//
//		// use mockedLocker in code that requires Locker
//		// and then make assertions.
//
//	}
type MoqLocker struct {
	// WithLockFunc mocks the WithLock method.
	WithLockFunc func(ctx context.Context, path string, fn func() error) error

	// calls tracks calls to the methods.
	calls struct {
		// WithLock holds details about calls to the WithLock method.
		WithLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Fn is the fn argument value.
			Fn func() error
		}
	}
	lockWithLock sync.RWMutex
}

// WithLock calls WithLockFunc.
func (mock *MoqLocker) WithLock(ctx context.Context, path string, fn func() error) error {
	if mock.WithLockFunc == nil {
		panic("MoqLocker.WithLockFunc: method is nil but Locker.WithLock was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
		Fn   func() error
	}{
		Ctx:  ctx,
		Path: path,
		Fn:   fn,
	}
	mock.lockWithLock.Lock()
	mock.calls.WithLock = append(mock.calls.WithLock, callInfo)
	mock.lockWithLock.Unlock()
	return mock.WithLockFunc(ctx, path, fn)
}

// WithLockCalls gets all the calls that were made to WithLock.
// Check the length with:
//
//	len(mockedLocker.WithLockCalls())
func (mock *MoqLocker) WithLockCalls() []struct {
	Ctx  context.Context
	Path string
	Fn   func() error
} {
	var calls []struct {
		Ctx  context.Context
		Path string
		Fn   func() error
	}
	mock.lockWithLock.RLock()
	calls = mock.calls.WithLock
	mock.lockWithLock.RUnlock()
	return calls
}
