// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package exporter

import (
	"context"
	"sync"
)

// Ensure that MoqDispatcher does implement Dispatcher.
// If this is not the case, regenerate this file with mockery.
var _ Dispatcher = &MoqDispatcher{}

// MoqDispatcher is a mock implementation of Dispatcher.
//
//	func TestSomethingThatUsesDispatcher(t *testing.T) {
//
//		// make and configure a mocked Dispatcher
//		mockedDispatcher := &MoqDispatcher{
//			ApplyFunc: func(ctx context.Context, agent string, req *ApplyRequest) (*ApplyResponse, error) {
//				panic("mock out the Apply method")
//			},
//			InfoFunc: func(ctx context.Context, agent string) (*InfoResponse, error) {
//				panic("mock out the Info method")
//			},
//			ListAvailableFunc: func(ctx context.Context) ([]InfoResponse, error) {
//				panic("mock out the ListAvailable method")
//			},
//			RemoveFunc: func(ctx context.Context, agent string, req *RemoveRequest) (*RemoveResponse, error) {
//				panic("mock out the Remove method")
//			},
//		}
//
//		// use mockedDispatcher in code that requires Dispatcher
//		// and then make assertions.
//
//	}
type MoqDispatcher struct {
	// ApplyFunc mocks the Apply method.
	ApplyFunc func(ctx context.Context, agent string, req *ApplyRequest) (*ApplyResponse, error)

	// InfoFunc mocks the Info method.
	InfoFunc func(ctx context.Context, agent string) (*InfoResponse, error)

	// ListAvailableFunc mocks the ListAvailable method.
	ListAvailableFunc func(ctx context.Context) ([]InfoResponse, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, agent string, req *RemoveRequest) (*RemoveResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Apply holds details about calls to the Apply method.
		Apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Agent is the agent argument value.
			Agent string
			// Req is the req argument value.
			Req *ApplyRequest
		}
		// Info holds details about calls to the Info method.
		Info []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Agent is the agent argument value.
			Agent string
		}
		// ListAvailable holds details about calls to the ListAvailable method.
		ListAvailable []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Agent is the agent argument value.
			Agent string
			// Req is the req argument value.
			Req *RemoveRequest
		}
	}
	lockApply         sync.RWMutex
	lockInfo          sync.RWMutex
	lockListAvailable sync.RWMutex
	lockRemove        sync.RWMutex
}

// Apply calls ApplyFunc.
func (mock *MoqDispatcher) Apply(ctx context.Context, agent string, req *ApplyRequest) (*ApplyResponse, error) {
	if mock.ApplyFunc == nil {
		panic("MoqDispatcher.ApplyFunc: method is nil but Dispatcher.Apply was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Agent string
		Req   *ApplyRequest
	}{
		Ctx:   ctx,
		Agent: agent,
		Req:   req,
	}
	mock.lockApply.Lock()
	mock.calls.Apply = append(mock.calls.Apply, callInfo)
	mock.lockApply.Unlock()
	return mock.ApplyFunc(ctx, agent, req)
}

// ApplyCalls gets all the calls that were made to Apply.
// Check the length with:
//
//	len(mockedDispatcher.ApplyCalls())
func (mock *MoqDispatcher) ApplyCalls() []struct {
	Ctx   context.Context
	Agent string
	Req   *ApplyRequest
} {
	var calls []struct {
		Ctx   context.Context
		Agent string
		Req   *ApplyRequest
	}
	mock.lockApply.RLock()
	calls = mock.calls.Apply
	mock.lockApply.RUnlock()
	return calls
}

// Info calls InfoFunc.
func (mock *MoqDispatcher) Info(ctx context.Context, agent string) (*InfoResponse, error) {
	if mock.InfoFunc == nil {
		panic("MoqDispatcher.InfoFunc: method is nil but Dispatcher.Info was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Agent string
	}{
		Ctx:   ctx,
		Agent: agent,
	}
	mock.lockInfo.Lock()
	mock.calls.Info = append(mock.calls.Info, callInfo)
	mock.lockInfo.Unlock()
	return mock.InfoFunc(ctx, agent)
}

// InfoCalls gets all the calls that were made to Info.
// Check the length with:
//
//	len(mockedDispatcher.InfoCalls())
func (mock *MoqDispatcher) InfoCalls() []struct {
	Ctx   context.Context
	Agent string
} {
	var calls []struct {
		Ctx   context.Context
		Agent string
	}
	mock.lockInfo.RLock()
	calls = mock.calls.Info
	mock.lockInfo.RUnlock()
	return calls
}

// ListAvailable calls ListAvailableFunc.
func (mock *MoqDispatcher) ListAvailable(ctx context.Context) ([]InfoResponse, error) {
	if mock.ListAvailableFunc == nil {
		panic("MoqDispatcher.ListAvailableFunc: method is nil but Dispatcher.ListAvailable was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListAvailable.Lock()
	mock.calls.ListAvailable = append(mock.calls.ListAvailable, callInfo)
	mock.lockListAvailable.Unlock()
	return mock.ListAvailableFunc(ctx)
}

// ListAvailableCalls gets all the calls that were made to ListAvailable.
// Check the length with:
//
//	len(mockedDispatcher.ListAvailableCalls())
func (mock *MoqDispatcher) ListAvailableCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListAvailable.RLock()
	calls = mock.calls.ListAvailable
	mock.lockListAvailable.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *MoqDispatcher) Remove(ctx context.Context, agent string, req *RemoveRequest) (*RemoveResponse, error) {
	if mock.RemoveFunc == nil {
		panic("MoqDispatcher.RemoveFunc: method is nil but Dispatcher.Remove was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Agent string
		Req   *RemoveRequest
	}{
		Ctx:   ctx,
		Agent: agent,
		Req:   req,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(ctx, agent, req)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedDispatcher.RemoveCalls())
func (mock *MoqDispatcher) RemoveCalls() []struct {
	Ctx   context.Context
	Agent string
	Req   *RemoveRequest
} {
	var calls []struct {
		Ctx   context.Context
		Agent string
		Req   *RemoveRequest
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}
