// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package exporter

import (
	"context"
	"sync"
)

// Ensure that Moqexporter does implement exporter.
// If this is not the case, regenerate this file with mockery.
var _ exporter = &Moqexporter{}

// Moqexporter is a mock implementation of exporter.
//
//	func TestSomethingThatUsesexporter(t *testing.T) {
//
//		// make and configure a mocked exporter
//		mockedexporter := &Moqexporter{
//			applyFunc: func(ctx context.Context, req *ApplyRequest) (*ApplyResponse, error) {
//				panic("mock out the apply method")
//			},
//		}
//
//		// use mockedexporter in code that requires exporter
//		// and then make assertions.
//
//	}
type Moqexporter struct {
	// applyFunc mocks the apply method.
	applyFunc func(ctx context.Context, req *ApplyRequest) (*ApplyResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// apply holds details about calls to the apply method.
		apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *ApplyRequest
		}
	}
	lockapply sync.RWMutex
}

// apply calls applyFunc.
func (mock *Moqexporter) apply(ctx context.Context, req *ApplyRequest) (*ApplyResponse, error) {
	if mock.applyFunc == nil {
		panic("Moqexporter.applyFunc: method is nil but exporter.apply was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *ApplyRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockapply.Lock()
	mock.calls.apply = append(mock.calls.apply, callInfo)
	mock.lockapply.Unlock()
	return mock.applyFunc(ctx, req)
}

// applyCalls gets all the calls that were made to apply.
// Check the length with:
//
//	len(mockedexporter.applyCalls())
func (mock *Moqexporter) applyCalls() []struct {
	Ctx context.Context
	Req *ApplyRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *ApplyRequest
	}
	mock.lockapply.RLock()
	calls = mock.calls.apply
	mock.lockapply.RUnlock()
	return calls
}
