// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package exporter

import (
	"context"
	"sync"
)

// Ensure that Moqexporter does implement exporter.
// If this is not the case, regenerate this file with mockery.
var _ exporter = &Moqexporter{}

// Moqexporter is a mock implementation of exporter.
//
//	func TestSomethingThatUsesexporter(t *testing.T) {
//
//		// make and configure a mocked exporter
//		mockedexporter := &Moqexporter{
//			applyFunc: func(ctx context.Context, req *ApplyRequest) (*ApplyResponse, error) {
//				panic("mock out the apply method")
//			},
//			infoFunc: func(ctx context.Context) (*InfoResponse, error) {
//				panic("mock out the info method")
//			},
//			removeFunc: func(ctx context.Context, req *RemoveRequest) (*RemoveResponse, error) {
//				panic("mock out the remove method")
//			},
//		}
//
//		// use mockedexporter in code that requires exporter
//		// and then make assertions.
//
//	}
type Moqexporter struct {
	// applyFunc mocks the apply method.
	applyFunc func(ctx context.Context, req *ApplyRequest) (*ApplyResponse, error)

	// infoFunc mocks the info method.
	infoFunc func(ctx context.Context) (*InfoResponse, error)

	// removeFunc mocks the remove method.
	removeFunc func(ctx context.Context, req *RemoveRequest) (*RemoveResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// apply holds details about calls to the apply method.
		apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *ApplyRequest
		}
		// info holds details about calls to the info method.
		info []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// remove holds details about calls to the remove method.
		remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *RemoveRequest
		}
	}
	lockapply  sync.RWMutex
	lockinfo   sync.RWMutex
	lockremove sync.RWMutex
}

// apply calls applyFunc.
func (mock *Moqexporter) apply(ctx context.Context, req *ApplyRequest) (*ApplyResponse, error) {
	if mock.applyFunc == nil {
		panic("Moqexporter.applyFunc: method is nil but exporter.apply was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *ApplyRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockapply.Lock()
	mock.calls.apply = append(mock.calls.apply, callInfo)
	mock.lockapply.Unlock()
	return mock.applyFunc(ctx, req)
}

// applyCalls gets all the calls that were made to apply.
// Check the length with:
//
//	len(mockedexporter.applyCalls())
func (mock *Moqexporter) applyCalls() []struct {
	Ctx context.Context
	Req *ApplyRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *ApplyRequest
	}
	mock.lockapply.RLock()
	calls = mock.calls.apply
	mock.lockapply.RUnlock()
	return calls
}

// info calls infoFunc.
func (mock *Moqexporter) info(ctx context.Context) (*InfoResponse, error) {
	if mock.infoFunc == nil {
		panic("Moqexporter.infoFunc: method is nil but exporter.info was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockinfo.Lock()
	mock.calls.info = append(mock.calls.info, callInfo)
	mock.lockinfo.Unlock()
	return mock.infoFunc(ctx)
}

// infoCalls gets all the calls that were made to info.
// Check the length with:
//
//	len(mockedexporter.infoCalls())
func (mock *Moqexporter) infoCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockinfo.RLock()
	calls = mock.calls.info
	mock.lockinfo.RUnlock()
	return calls
}

// remove calls removeFunc.
func (mock *Moqexporter) remove(ctx context.Context, req *RemoveRequest) (*RemoveResponse, error) {
	if mock.removeFunc == nil {
		panic("Moqexporter.removeFunc: method is nil but exporter.remove was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *RemoveRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockremove.Lock()
	mock.calls.remove = append(mock.calls.remove, callInfo)
	mock.lockremove.Unlock()
	return mock.removeFunc(ctx, req)
}

// removeCalls gets all the calls that were made to remove.
// Check the length with:
//
//	len(mockedexporter.removeCalls())
func (mock *Moqexporter) removeCalls() []struct {
	Ctx context.Context
	Req *RemoveRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *RemoveRequest
	}
	mock.lockremove.RLock()
	calls = mock.calls.remove
	mock.lockremove.RUnlock()
	return calls
}
